/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sofyan
 */

import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Transaksi extends javax.swing.JFrame {
    /**
     * Creates new form Transaksi
     */
    
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.BukaKoneksi();
    public Transaksi() {
        initComponents();
        TampilData();
        TampilComboPelanggan();
        TampilComboWisata();
    }
    
    private void Bersih(){
        txt_IdTransaksi.setText("");
        txt_BiayaWisata.setText("");
        combo_Pelanggan.setSelectedItem(0);
        combo_Wisata.setSelectedItem(0);
        txt_Tanggal.setText("");
        
        button_Simpan.setText("SIMPAN");
        txt_IdTransaksi.setEditable(true);
    }
    
    private void TampilData(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM transaksi");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("id_transaksi");
            model.addColumn("nama_pelanggan");
            model.addColumn("nama_wisata");
            model.addColumn("tanggal");
            model.addColumn("biaya_wisata");
            
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while(rs.next()){
                Object[] data = {
                  rs.getString("id_transaksi"),
                  rs.getString("nama_pelanggan"),
                  rs.getString("nama_wisata"),
                  rs.getString("tanggal"),
                  rs.getString("biaya_wisata")
                };
                model.addRow(data);
                table_Transaksi.setModel(model);
            }
        } catch (Exception e){
            
        }
    }
    
    public void TampilComboPelanggan(){
        try{
            String sql = "SELECT * FROM pelanggan";
            java.sql.Connection conn = (Connection) koneksi.BukaKoneksi();
            java.sql.PreparedStatement pst = conn.prepareCall(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                combo_Pelanggan.addItem(rs.getString("nama_pelanggan"));
            }
            rs.last();
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void TampilComboWisata(){
        try{
            String sql = "SELECT * FROM wisata";
            java.sql.Connection conn = (Connection) koneksi.BukaKoneksi();
            java.sql.PreparedStatement pst = conn.prepareCall(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                combo_Wisata.addItem(rs.getString("nama_wisata")); 
            }
            rs.last();
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void SetBiayaWisata(){
            try {
            // TODO add your handling code here:
            java.sql.Connection con = (Connection) koneksi.BukaKoneksi();
            String SQL = "SELECT biaya_wisata FROM wisata WHERE nama_wisata = '" + combo_Wisata.getSelectedItem() + "'";
            ResultSet rs = con.createStatement().executeQuery(SQL);
            while(rs.next()){
                txt_BiayaWisata.setText(rs.getString("biaya_wisata"));
            }
            rs.last();
        } catch (Exception e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_BiayaWisata = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Transaksi = new javax.swing.JTable();
        button_Simpan = new javax.swing.JButton();
        button_Batal = new javax.swing.JButton();
        button_Hapus = new javax.swing.JButton();
        button_Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_IdTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_Pelanggan = new javax.swing.JComboBox<>();
        combo_Wisata = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Tanggal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Pelanggan");

        jLabel2.setText("Biaya Wisata");

        table_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Nama Wisata", "Nama Pelanggan", "Tanggal", "Biaya"
            }
        ));
        table_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_TransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Transaksi);

        button_Simpan.setText("SIMPAN");
        button_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SimpanActionPerformed(evt);
            }
        });

        button_Batal.setText("BATAL");
        button_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BatalActionPerformed(evt);
            }
        });

        button_Hapus.setText("HAPUS");
        button_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HapusActionPerformed(evt);
            }
        });

        button_Kembali.setText("KEMBALI");
        button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_KembaliActionPerformed(evt);
            }
        });

        jLabel4.setText("ID transaksi");

        jLabel3.setText("Pilih Wisata");

        combo_Wisata.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_WisataItemStateChanged(evt);
            }
        });

        jButton1.setText("CETAK LAPORAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("INPUT TRANSAKSI WISATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_Kembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(138, 138, 138)
                                .addComponent(button_Hapus))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_IdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_Wisata, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_BiayaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Simpan)
                .addGap(118, 118, 118)
                .addComponent(button_Batal)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_IdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_Wisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BiayaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Simpan)
                    .addComponent(button_Batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Hapus)
                    .addComponent(button_Kembali)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SimpanActionPerformed
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            if (txt_BiayaWisata.getText().equals("") || txt_IdTransaksi.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            //aksi simpan data
            if(button_Simpan.getText() == "SIMPAN") {
                String cek = "SELECT * FROM transaksi WHERE id_transaksi = '" + txt_IdTransaksi.getText() + "'";
                rs = st.executeQuery(cek);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Ups... id ini sudah ada");
                }else{
                    String sql = "INSERT INTO transaksi VALUES ('" + txt_IdTransaksi.getText() + "','" + combo_Pelanggan.getSelectedItem() + "','" + combo_Wisata.getSelectedItem() + "','" + 
                            txt_Tanggal.getText() + "','" + txt_BiayaWisata.getText()+ "')";
                            
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                    Bersih();
                    TampilData();
                }
            }else{
                //aksi ubah data
                String update = "UPDATE transaksi SET nama_wisata = '" + combo_Wisata.getSelectedItem() + "', biaya_wisata = '" + txt_BiayaWisata.getText() + "', nama_pelanggan = '" + combo_Pelanggan.getSelectedItem() + "' WHERE id_transaksi = '" + txt_IdTransaksi.getText() + "'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                Bersih();
                TampilData();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_button_SimpanActionPerformed

    private void table_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_TransaksiMouseClicked
        // TODO add your handling code here:
        txt_IdTransaksi.setText(table_Transaksi.getValueAt(table_Transaksi.getSelectedRow(), 0).toString());
        combo_Pelanggan.setSelectedItem(table_Transaksi.getValueAt(table_Transaksi.getSelectedRow(), 1).toString());
        combo_Wisata.setSelectedItem(table_Transaksi.getValueAt(table_Transaksi.getSelectedRow(), 2).toString());
        txt_Tanggal.setText(table_Transaksi.getValueAt(table_Transaksi.getSelectedRow(), 3).toString());
        txt_BiayaWisata.setText(table_Transaksi.getValueAt(table_Transaksi.getSelectedRow(), 4).toString());
        
        txt_IdTransaksi.setEditable(false);
        button_Simpan.setText("UBAH");
    }//GEN-LAST:event_table_TransaksiMouseClicked

    private void button_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HapusActionPerformed
        // TODO add your handling code here:
        if(txt_IdTransaksi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus !");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, lanjutkan ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try{
                    st = cn.createStatement();
                    String sql = "DELETE FROM transaksi WHERE id_transaksi = '" + txt_IdTransaksi.getText() + "'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    TampilData();
                    Bersih();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
        }
        }
    }//GEN-LAST:event_button_HapusActionPerformed

    private void button_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BatalActionPerformed
        // TODO add your handling code here:
        Bersih();
    }//GEN-LAST:event_button_BatalActionPerformed

    private void combo_WisataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_WisataItemStateChanged
        // TODO add your handling code here:
        SetBiayaWisata();
    }//GEN-LAST:event_combo_WisataItemStateChanged

    private void button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_KembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_button_KembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:" + "///tour", "root", "");
            File file = new File("src/LaporanTransaksi.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Data tidak dapat di Cetak !!!" + "\n" + e.getMessage(), "Cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Batal;
    private javax.swing.JButton button_Hapus;
    private javax.swing.JButton button_Kembali;
    private javax.swing.JButton button_Simpan;
    private javax.swing.JComboBox<String> combo_Pelanggan;
    private javax.swing.JComboBox<String> combo_Wisata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Transaksi;
    private javax.swing.JTextField txt_BiayaWisata;
    private javax.swing.JTextField txt_IdTransaksi;
    private javax.swing.JTextField txt_Tanggal;
    // End of variables declaration//GEN-END:variables
}
